# vim: ft=yaml
---
repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: Check shell scripts with shellcheck
        files: ^.*\.(sh|bash|ksh)$
        types: []
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: Check YAML syntax with yamllint
        args: [--strict]
        types: [file]
        # Files to include
        # 1. Obvious YAML files
        # 2. `pillar.example` and similar files
        # 3. SLS files under directory `test/` which are pillar files
        # Files to exclude
        # 1. SLS files under directory `test/` which are state files
        # 2. `kitchen.vagrant.yml`, which contains Embedded Ruby (ERB) template syntax
        # 3. YAML files heavily reliant on Jinja
        files: |
          (?x)^(
                .*\.yaml|
                .*\.yml|
                \.salt-lint|
                \.yamllint|
                .*\.example|
          )$
        exclude: |
          (?x)^(
                .copier-answers.yml|
          )$
  - repo: https://github.com/warpnet/salt-lint
    rev: v0.9.2
    hooks:
      - id: salt-lint
        name: Check Salt files using salt-lint
        files: ^.*\.(sls|jinja|j2|tmpl|tst)$
  - repo: local
    hooks:
      - id: slsdoc
        name: Dump state documentation with slsdoc
        entry: ./bin/slsdoc
        language: system
        require_serial: true
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: render_readme
        name: Render available states in README.rst.tpl
        entry: ./bin/render_readme
        language: system
        require_serial: true
        always_run: true
        pass_filenames: false
  - repo: https://github.com/myint/rstcheck
    rev: v6.2.0
    hooks:
      - id: rstcheck
        name: Check reST files using rstcheck
        exclude: 'docs/CHANGELOG.rst'
        additional_dependencies: [sphinx==7.2.6]
  - repo: https://github.com/saltstack-formulas/mirrors-rst-lint
    rev: v1.3.2
    hooks:
      - id: rst-lint
        name: Check reST files using rst-lint
        exclude: |
            (?x)^(
                docs/CHANGELOG.rst|
                docs/TOFS_pattern.rst|
                docs/CONTRIBUTING_DOCS.rst|
                docs/index.rst|
                docs/pillar.rst|
            )$
        additional_dependencies: [pygments==2.16.1]
